### ISSUE TITLE
Podatki z vrednostjo 0

### ISSUE THREAD

**Issue by StangeljL12** [StangeljL12/APPR-2015-16#1]
Uvožene imam podatke, ki prikazujejo število porok. Zanima me, ali tam kjer je podatek 0, pustim število 0, ali moram spremeniti v NA?

**Comment by jaanos** [comment]
Če je podatek že 0, potem ga pusti kot takega. NA naj bo samo tam,
kjer podatek manjka (ponavadi je posebej označen, npr. z - ali N -
morda tudi v komentarjih k podatkom piše, kaj kaj pomeni).
1. 09. 16 je StangeljL12 notifications@github.com napisal/-a:
